### ISSUE TITLE
REQ: lokaal draaien van de opgaves

### ISSUE THREAD

**Issue by nickstolwijk** [First8/mastersofjava#22]
Ik zou graag de opgaves met m'n eigen team willen draaien, maar het is onduidelijk hoe ik aan de software kom om dit te kunnen doen. Is de nieuwe software ook ergens beschikbaar?

**Comment by alamers** [comment]
Die is zeker beschikbaar: https://github.com/mastersofjava/mastersofjava

Als er vragen zijn, laat maar weten. Documentatie kan wat beperkt zijn 😳

**Comment by nickstolwijk** [comment]
Bedankt! Ik kon hem echt niet vinden. Misschien goed om op te nemen in de readme?

**Comment by alamers** [comment]
Ik was er al mee bezig ;) Mocht je nog tegen dingen aanlopen, dan breid ik eea nog meteen uit!
